# ===================================
#  List Behavior Config
# ===================================

title: system::lang.bot_log.menu_label
list: ~/modules/system/models/botlog/columns.yaml
modelClass: System\Models\BotLog
recordUrl: system/botlogs/preview/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 30
showSetup: true
showCheckboxes: true
defaultSort:
    column: count
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt