# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: system::lang.bot_log.menu_label

# Model Form Field configuration
form: ~/modules/system/models/botlog/fields.yaml

# Model Class name
modelClass: System\Models\BotLog

# Default redirect location
defaultRedirect: system/botlogs

# Preview page
preview:
    title: system::lang.bot_log.preview_title